blank_issues_enabled: false
contact_links:
  - name: Ideas Discussions | 💡
    url: https://github.com/melontini/Linkart/discussions/categories/ideas
    about: If you have a suggestion, please post it there.
