
name: publish
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "The type of this version. e.g alpha"
        type: choice
        default: beta
        options:
          - release
          - beta
          - alpha
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.1
      - name: Setup JDK 17
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Retrieve version #https://stackoverflow.com/questions/71089787/how-to-get-version-name-from-android-gradle-file-in-github-actions
        run: |
          echo "VERSION_INFORMATION=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_ENV
          echo "VERSION_PLAIN=$(${{github.workspace}}/gradlew -q printVersion)" >> $GITHUB_ENV
          echo "GAME_VERSIONS=$(${{github.workspace}}/gradlew -q printGameVersions)" >> $GITHUB_ENV
      - name: Publish Minecraft mods
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          version-type: ${{ inputs.version_type }}
          changelog-file: CHANGELOG.md
          name: ${{ env.VERSION_INFORMATION }}
          version: ${{ env.VERSION_PLAIN }}

          game-versions: |
            ${{ env.GAME_VERSIONS }}

          loaders: |
            fabric

          java: |
            17

          github-tag: v${{ env.VERSION_PLAIN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-commitish: ${{ github.sha }}
          github-prerelease: false

          modrinth-id: sc4Mu9Zu
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-dependencies: |
            fabric-api(required)


          curseforge-id: 622736
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-dependencies: |
            fabric-api(required)
